/** Rutas relativas a VITE_API_URL. Centralizadas para un único punto de cambio. */
export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    actualizarPerfil: '/auth/me',
    changePassword: '/auth/change-password',
    resetPassword: '/auth/reset-password',
  },
  categorias: '/categorias',
  categoria: (id: string) => `/categorias/${id}`,
  categoriaActivo: (id: string) => `/categorias/${id}/activo`,
  categoriaEstadoDeuda: (id: string) => `/categorias/${id}/estado-deuda`,
  categoriaCobertura: (id: string) => `/categorias/${id}/cobertura`,
  periodos: '/periodos',
  periodo: (id: string) => `/periodos/${id}`,
  periodoIniciar: (id: string) => `/periodos/${id}/iniciar`,
  periodoResumen: (id: string) => `/periodos/${id}/resumen`,
  movimientos: '/movimientos',
  movimiento: (id: string) => `/movimientos/${id}`,
  metas: '/metas',
  meta: (id: string) => `/metas/${id}`,
  metaActivo: (id: string) => `/metas/${id}/activo`,
  metaAportes: (id: string) => `/metas/${id}/aportes`,
  configuracion: '/configuracion',
  dashboard: '/dashboard',
  proyeccion: '/proyeccion',
  deudas: '/deudas',
  usuarios: '/usuarios',
} as const;
